### ISSUE TITLE
"Interact" convolution demo isn't working properly

### ISSUE THREAD

**Issue by jni** [sofroniewn/tutorial-scipy2021-bioimage-analysis-fundamentals#4]
On my Linux machine and a fresh environment, scrolling through the slider creates a new figure for each new timepoint, resulting in an enormous output cell with hundreds of images.

**Comment by jni** [comment]
(Cell 8 in the Filtering notebook)

**Comment by jni** [comment]
The image convolution (Cell 29) works fine though, so it's worth thinking about what is different between those. Is it a plt.show() call?

**Comment by sofroniewn** [comment]
hmm ok weird, will look

**Comment by sofroniewn** [comment]
yup, happens to me too - didn't use to, so def a change in a dependency ...

**Comment by sofroniewn** [comment]
`plt.show()` fixes!!
