### ISSUE TITLE
environment.yml python version

### ISSUE THREAD

**Issue by bjlittle** [sofroniewn/tutorial-scipy2021-bioimage-analysis-fundamentals#5]
@jni and @sofroniewn 

Really looking forward to the SciPy2021 tutorial later today... good luck guys! :+1: 

I'm just setting up my environment for the tutorial but noticed in the `README.md` that you recommend using `py38`, but the `environment.yml` is pinned to `py39`... I'm guessing this doesn't greatly matter, right?

**Comment by sofroniewn** [comment]
Ah yes, thanks - will fix. Only recently made that change, but it shouldn't matter!!
